import { OpencodeModels } from "ai-sdk-provider-opencode-sdk";
import type {
  InferenceProviderAuthMode,
  InferenceProviderCatalogAccessMode,
  InferenceProviderCatalogFamily,
  InferenceProviderId,
} from "@secretary/core-runtime";

export type InferenceRuntimeKind =
  | "openai"
  | "anthropic"
  | "google"
  | "google_vertex"
  | "xai"
  | "moonshot"
  | "mistral"
  | "togetherai"
  | "cohere"
  | "fireworks"
  | "deepinfra"
  | "deepseek"
  | "cerebras"
  | "groq"
  | "perplexity"
  | "azure"
  | "amazon_bedrock"
  | "baseten"
  | "vercel"
  | "huggingface"
  | "openrouter"
  | "ollama"
  | "openai_compatible"
  | "opencode"
  | "opencode_zen"
  | "opencode_go"
  | "codex_cli"
  | "gemini_cli"
  | "claude_code";

export type InferenceProviderDefinition = {
  id: InferenceProviderId;
  label: string;
  description: string;
  authMode: InferenceProviderAuthMode;
  docsUrl: string;
  packageName: string | null;
  providerFamily: InferenceProviderCatalogFamily;
  accessMode: InferenceProviderCatalogAccessMode;
  availableInApp: boolean;
  defaultBaseUrl: string | null;
  defaultModel: string | null;
  defaultMaxOutputTokens: number;
  supportsModelFetch: boolean;
  supportsReasoningEffort: boolean;
  runtimeKind: InferenceRuntimeKind;
};

const docsBase = "https://ai-sdk.dev";

export const inferenceProviderDefinitions: InferenceProviderDefinition[] = [
  {
    id: "openai",
    label: "OpenAI",
    description: "Direct OpenAI provider through the AI SDK.",
    authMode: "api_key",
    docsUrl: `${docsBase}/providers/ai-sdk-providers/openai`,
    packageName: "@ai-sdk/openai",
    providerFamily: "ai_sdk_provider",
    accessMode: "direct_api",
    availableInApp: true,
    defaultBaseUrl: null,
    defaultModel: "gpt-5.4",
    defaultMaxOutputTokens: 1200,
    supportsModelFetch: true,
    supportsReasoningEffort: true,
    runtimeKind: "openai",
  },
  {
    id: "anthropic",
    label: "Anthropic",
    description: "Direct Anthropic provider through the AI SDK.",
    authMode: "api_key",
    docsUrl: `${docsBase}/providers/ai-sdk-providers/anthropic`,
    packageName: "@ai-sdk/anthropic",
    providerFamily: "ai_sdk_provider",
    accessMode: "direct_api",
    availableInApp: true,
    defaultBaseUrl: "https://api.anthropic.com/v1",
    defaultModel: "claude-sonnet-4-6",
    defaultMaxOutputTokens: 1400,
    supportsModelFetch: false,
    supportsReasoningEffort: false,
    runtimeKind: "anthropic",
  },
  {
    id: "google",
    label: "Google Generative AI",
    description: "Direct Google Generative AI provider through the AI SDK.",
    authMode: "api_key",
    docsUrl: `${docsBase}/providers/ai-sdk-providers/google-generative-ai`,
    packageName: "@ai-sdk/google",
    providerFamily: "ai_sdk_provider",
    accessMode: "direct_api",
    availableInApp: true,
    defaultBaseUrl: "https://generativelanguage.googleapis.com/v1beta",
    defaultModel: "gemini-3.1-pro-preview",
    defaultMaxOutputTokens: 1200,
    supportsModelFetch: false,
    supportsReasoningEffort: false,
    runtimeKind: "google",
  },
  {
    id: "google_vertex",
    label: "Google Vertex",
    description: "Vertex AI with API key or ambient Google Cloud authentication.",
    authMode: "api_key_or_account",
    docsUrl: `${docsBase}/providers/ai-sdk-providers/google-vertex`,
    packageName: "@ai-sdk/google-vertex",
    providerFamily: "ai_sdk_provider",
    accessMode: "direct_api",
    availableInApp: true,
    defaultBaseUrl: null,
    defaultModel: "gemini-3.1-pro-preview",
    defaultMaxOutputTokens: 1200,
    supportsModelFetch: false,
    supportsReasoningEffort: false,
    runtimeKind: "google_vertex",
  },
  {
    id: "xai",
    label: "xAI Grok",
    description: "Direct xAI provider through the AI SDK.",
    authMode: "api_key",
    docsUrl: `${docsBase}/providers/ai-sdk-providers/xai`,
    packageName: "@ai-sdk/xai",
    providerFamily: "ai_sdk_provider",
    accessMode: "direct_api",
    availableInApp: true,
    defaultBaseUrl: "https://api.x.ai/v1",
    defaultModel: "grok-4",
    defaultMaxOutputTokens: 1200,
    supportsModelFetch: true,
    supportsReasoningEffort: true,
    runtimeKind: "xai",
  },
  {
    id: "moonshot",
    label: "Kimi Code (Moonshot)",
    description: "Kimi Code API via the OpenAI-compatible endpoint. Use your Kimi Code API key.",
    authMode: "api_key",
    docsUrl: `${docsBase}/providers/openai-compatible-providers`,
    packageName: "@ai-sdk/openai-compatible",
    providerFamily: "openai_compatible",
    accessMode: "direct_api",
    availableInApp: true,
    defaultBaseUrl: "https://api.kimi.com/coding/v1",
    defaultModel: "kimi-for-coding",
    defaultMaxOutputTokens: 900,
    supportsModelFetch: true,
    supportsReasoningEffort: false,
    runtimeKind: "moonshot",
  },
  {
    id: "mistral",
    label: "Mistral",
    description: "Direct Mistral provider through the AI SDK.",
    authMode: "api_key",
    docsUrl: `${docsBase}/providers/ai-sdk-providers/mistral`,
    packageName: "@ai-sdk/mistral",
    providerFamily: "ai_sdk_provider",
    accessMode: "direct_api",
    availableInApp: true,
    defaultBaseUrl: null,
    defaultModel: "mistral-large-latest",
    defaultMaxOutputTokens: 1200,
    supportsModelFetch: false,
    supportsReasoningEffort: false,
    runtimeKind: "mistral",
  },
  {
    id: "togetherai",
    label: "Together.ai",
    description: "Direct Together.ai provider through the AI SDK.",
    authMode: "api_key",
    docsUrl: `${docsBase}/providers/ai-sdk-providers/togetherai`,
    packageName: "@ai-sdk/togetherai",
    providerFamily: "ai_sdk_provider",
    accessMode: "direct_api",
    availableInApp: true,
    defaultBaseUrl: null,
    defaultModel: null,
    defaultMaxOutputTokens: 1000,
    supportsModelFetch: true,
    supportsReasoningEffort: false,
    runtimeKind: "togetherai",
  },
  {
    id: "cohere",
    label: "Cohere",
    description: "Direct Cohere provider through the AI SDK.",
    authMode: "api_key",
    docsUrl: `${docsBase}/providers/ai-sdk-providers/cohere`,
    packageName: "@ai-sdk/cohere",
    providerFamily: "ai_sdk_provider",
    accessMode: "direct_api",
    availableInApp: true,
    defaultBaseUrl: null,
    defaultModel: null,
    defaultMaxOutputTokens: 1000,
    supportsModelFetch: false,
    supportsReasoningEffort: false,
    runtimeKind: "cohere",
  },
  {
    id: "fireworks",
    label: "Fireworks",
    description: "Direct Fireworks provider through the AI SDK.",
    authMode: "api_key",
    docsUrl: `${docsBase}/providers/ai-sdk-providers/fireworks`,
    packageName: "@ai-sdk/fireworks",
    providerFamily: "ai_sdk_provider",
    accessMode: "direct_api",
    availableInApp: true,
    defaultBaseUrl: null,
    defaultModel: null,
    defaultMaxOutputTokens: 1000,
    supportsModelFetch: true,
    supportsReasoningEffort: false,
    runtimeKind: "fireworks",
  },
  {
    id: "deepinfra",
    label: "DeepInfra",
    description: "Direct DeepInfra provider through the AI SDK.",
    authMode: "api_key",
    docsUrl: `${docsBase}/providers/ai-sdk-providers/deepinfra`,
    packageName: "@ai-sdk/deepinfra",
    providerFamily: "ai_sdk_provider",
    accessMode: "direct_api",
    availableInApp: true,
    defaultBaseUrl: null,
    defaultModel: null,
    defaultMaxOutputTokens: 1000,
    supportsModelFetch: false,
    supportsReasoningEffort: false,
    runtimeKind: "deepinfra",
  },
  {
    id: "deepseek",
    label: "DeepSeek",
    description: "Direct DeepSeek provider through the AI SDK.",
    authMode: "api_key",
    docsUrl: `${docsBase}/providers/ai-sdk-providers/deepseek`,
    packageName: "@ai-sdk/deepseek",
    providerFamily: "ai_sdk_provider",
    accessMode: "direct_api",
    availableInApp: true,
    defaultBaseUrl: null,
    defaultModel: "deepseek-chat",
    defaultMaxOutputTokens: 1000,
    supportsModelFetch: true,
    supportsReasoningEffort: false,
    runtimeKind: "deepseek",
  },
  {
    id: "cerebras",
    label: "Cerebras",
    description: "Direct Cerebras provider through the AI SDK.",
    authMode: "api_key",
    docsUrl: `${docsBase}/providers/ai-sdk-providers/cerebras`,
    packageName: "@ai-sdk/cerebras",
    providerFamily: "ai_sdk_provider",
    accessMode: "direct_api",
    availableInApp: true,
    defaultBaseUrl: null,
    defaultModel: null,
    defaultMaxOutputTokens: 1000,
    supportsModelFetch: false,
    supportsReasoningEffort: false,
    runtimeKind: "cerebras",
  },
  {
    id: "groq",
    label: "Groq",
    description: "Direct Groq provider through the AI SDK.",
    authMode: "api_key",
    docsUrl: `${docsBase}/providers/ai-sdk-providers/groq`,
    packageName: "@ai-sdk/groq",
    providerFamily: "ai_sdk_provider",
    accessMode: "direct_api",
    availableInApp: true,
    defaultBaseUrl: null,
    defaultModel: "llama-3.3-70b-versatile",
    defaultMaxOutputTokens: 1000,
    supportsModelFetch: true,
    supportsReasoningEffort: false,
    runtimeKind: "groq",
  },
  {
    id: "perplexity",
    label: "Perplexity",
    description: "Direct Perplexity provider through the AI SDK.",
    authMode: "api_key",
    docsUrl: `${docsBase}/providers/ai-sdk-providers/perplexity`,
    packageName: "@ai-sdk/perplexity",
    providerFamily: "ai_sdk_provider",
    accessMode: "direct_api",
    availableInApp: true,
    defaultBaseUrl: null,
    defaultModel: null,
    defaultMaxOutputTokens: 1000,
    supportsModelFetch: false,
    supportsReasoningEffort: false,
    runtimeKind: "perplexity",
  },
  {
    id: "azure",
    label: "Azure OpenAI",
    description: "Azure OpenAI through the official AI SDK provider.",
    authMode: "api_key",
    docsUrl: `${docsBase}/providers/ai-sdk-providers/azure`,
    packageName: "@ai-sdk/azure",
    providerFamily: "ai_sdk_provider",
    accessMode: "direct_api",
    availableInApp: true,
    defaultBaseUrl: null,
    defaultModel: null,
    defaultMaxOutputTokens: 1200,
    supportsModelFetch: false,
    supportsReasoningEffort: true,
    runtimeKind: "azure",
  },
  {
    id: "amazon_bedrock",
    label: "Amazon Bedrock",
    description: "Bedrock with bearer token, API key, or ambient AWS credentials.",
    authMode: "api_key_or_account",
    docsUrl: `${docsBase}/providers/ai-sdk-providers/amazon-bedrock`,
    packageName: "@ai-sdk/amazon-bedrock",
    providerFamily: "ai_sdk_provider",
    accessMode: "direct_api",
    availableInApp: true,
    defaultBaseUrl: null,
    defaultModel: null,
    defaultMaxOutputTokens: 1200,
    supportsModelFetch: false,
    supportsReasoningEffort: false,
    runtimeKind: "amazon_bedrock",
  },
  {
    id: "baseten",
    label: "Baseten",
    description: "Baseten model APIs through the official AI SDK provider.",
    authMode: "api_key",
    docsUrl: `${docsBase}/providers/ai-sdk-providers/baseten`,
    packageName: "@ai-sdk/baseten",
    providerFamily: "ai_sdk_provider",
    accessMode: "direct_api",
    availableInApp: true,
    defaultBaseUrl: "https://inference.baseten.co/v1",
    defaultModel: null,
    defaultMaxOutputTokens: 1000,
    supportsModelFetch: false,
    supportsReasoningEffort: false,
    runtimeKind: "baseten",
  },
  {
    id: "vercel",
    label: "Vercel",
    description: "Vercel-hosted models through the official AI SDK provider.",
    authMode: "api_key",
    docsUrl: `${docsBase}/providers/ai-sdk-providers/vercel`,
    packageName: "@ai-sdk/vercel",
    providerFamily: "ai_sdk_provider",
    accessMode: "direct_api",
    availableInApp: true,
    defaultBaseUrl: null,
    defaultModel: null,
    defaultMaxOutputTokens: 1000,
    supportsModelFetch: false,
    supportsReasoningEffort: false,
    runtimeKind: "vercel",
  },
  {
    id: "huggingface",
    label: "Hugging Face",
    description: "Hugging Face Inference Router through the AI SDK provider.",
    authMode: "api_key",
    docsUrl: `${docsBase}/providers/ai-sdk-providers/hugging-face`,
    packageName: "@ai-sdk/huggingface",
    providerFamily: "ai_sdk_provider",
    accessMode: "direct_api",
    availableInApp: true,
    defaultBaseUrl: "https://router.huggingface.co/v1",
    defaultModel: "Qwen/Qwen3-Coder-480B-A35B-Instruct",
    defaultMaxOutputTokens: 1000,
    supportsModelFetch: true,
    supportsReasoningEffort: false,
    runtimeKind: "huggingface",
  },
  {
    id: "openrouter",
    label: "OpenRouter",
    description: "OpenRouter routing layer through its community AI SDK provider.",
    authMode: "api_key",
    docsUrl: `${docsBase}/providers/community-providers/openrouter`,
    packageName: "@openrouter/ai-sdk-provider",
    providerFamily: "community",
    accessMode: "direct_api",
    availableInApp: true,
    defaultBaseUrl: "https://openrouter.ai/api/v1",
    defaultModel: "moonshotai/kimi-k2.5",
    defaultMaxOutputTokens: 1000,
    supportsModelFetch: true,
    supportsReasoningEffort: true,
    runtimeKind: "openrouter",
  },
  {
    id: "ollama_cloud",
    label: "Ollama Cloud",
    description: "Hosted Ollama account through its OpenAI-compatible API.",
    authMode: "api_key",
    docsUrl: `${docsBase}/providers/openai-compatible-providers`,
    packageName: "@ai-sdk/openai-compatible",
    providerFamily: "openai_compatible",
    accessMode: "direct_api",
    availableInApp: true,
    defaultBaseUrl: "https://ollama.com/v1",
    defaultModel: "qwen3:30b",
    defaultMaxOutputTokens: 1000,
    supportsModelFetch: true,
    supportsReasoningEffort: true,
    runtimeKind: "openai_compatible",
  },
  {
    id: "opencode",
    label: "OpenCode",
    description: "Local or account-authorized OpenCode runtime for subscription-backed access.",
    authMode: "account_authorized",
    docsUrl: `${docsBase}/providers/community-providers/opencode-sdk`,
    packageName: "ai-sdk-provider-opencode-sdk",
    providerFamily: "community",
    accessMode: "linked_account",
    availableInApp: true,
    defaultBaseUrl: "http://127.0.0.1:4096",
    defaultModel: OpencodeModels["claude-sonnet-4-5"],
    defaultMaxOutputTokens: 1000,
    supportsModelFetch: true,
    supportsReasoningEffort: false,
    runtimeKind: "opencode",
  },
  {
    id: "opencode_zen",
    label: "OpenCode Zen",
    description: "OpenCode Zen API key provider for curated pay-as-you-go models.",
    authMode: "api_key",
    docsUrl: "https://opencode.ai/docs/zen/",
    packageName: "@ai-sdk/openai-compatible",
    providerFamily: "openai_compatible",
    accessMode: "direct_api",
    availableInApp: true,
    defaultBaseUrl: "https://opencode.ai/zen/v1",
    defaultModel: null,
    defaultMaxOutputTokens: 1000,
    supportsModelFetch: true,
    supportsReasoningEffort: false,
    runtimeKind: "opencode_zen",
  },
  {
    id: "opencode_go",
    label: "OpenCode Go",
    description: "OpenCode Go API key provider for low-cost subscription models.",
    authMode: "api_key",
    docsUrl: "https://opencode.ai/docs/go/",
    packageName: "@ai-sdk/openai-compatible",
    providerFamily: "openai_compatible",
    accessMode: "direct_api",
    availableInApp: true,
    defaultBaseUrl: "https://opencode.ai/zen/go/v1",
    defaultModel: null,
    defaultMaxOutputTokens: 1000,
    supportsModelFetch: true,
    supportsReasoningEffort: false,
    runtimeKind: "opencode_go",
  },
  {
    id: "codex_cli",
    label: "Codex CLI",
    description: "ChatGPT subscription-backed or API-key-backed Codex CLI provider.",
    authMode: "account_authorized",
    docsUrl: `${docsBase}/providers/community-providers/codex-cli`,
    packageName: "ai-sdk-provider-codex-cli",
    providerFamily: "community",
    accessMode: "linked_account",
    availableInApp: true,
    defaultBaseUrl: null,
    defaultModel: "gpt-5.3-codex",
    defaultMaxOutputTokens: 1200,
    supportsModelFetch: true,
    supportsReasoningEffort: true,
    runtimeKind: "codex_cli",
  },
  {
    id: "gemini_cli",
    label: "Gemini CLI",
    description: "Gemini CLI provider for subscription-linked or API-key Gemini access.",
    authMode: "account_authorized",
    docsUrl: `${docsBase}/providers/community-providers/gemini-cli`,
    packageName: "ai-sdk-provider-gemini-cli",
    providerFamily: "community",
    accessMode: "linked_account",
    availableInApp: true,
    defaultBaseUrl: null,
    defaultModel: "gemini-3.1-pro-preview",
    defaultMaxOutputTokens: 1200,
    supportsModelFetch: false,
    supportsReasoningEffort: false,
    runtimeKind: "gemini_cli",
  },
  {
    id: "claude_code",
    label: "Claude Code",
    description: "Claude Code local/account-linked provider through the community SDK package.",
    authMode: "account_authorized",
    docsUrl: `${docsBase}/providers/community-providers/claude-code`,
    packageName: "ai-sdk-provider-claude-code",
    providerFamily: "community",
    accessMode: "linked_account",
    availableInApp: true,
    defaultBaseUrl: null,
    defaultModel: "sonnet",
    defaultMaxOutputTokens: 1200,
    supportsModelFetch: false,
    supportsReasoningEffort: false,
    runtimeKind: "claude_code",
  },
  {
    id: "ollama_local",
    label: "Ollama",
    description: "Direct local Ollama runtime on your machine or LAN.",
    authMode: "none",
    docsUrl: `${docsBase}/providers/community-providers/ollama`,
    packageName: "ollama-ai-provider-v2",
    providerFamily: "community",
    accessMode: "local_runtime",
    availableInApp: true,
    defaultBaseUrl: "http://127.0.0.1:11434",
    defaultModel: "qwen3:8b",
    defaultMaxOutputTokens: 900,
    supportsModelFetch: true,
    supportsReasoningEffort: false,
    runtimeKind: "ollama",
  },
  {
    id: "lmstudio",
    label: "LM Studio",
    description: "Local LM Studio runtime through the OpenAI-compatible provider path.",
    authMode: "none",
    docsUrl: `${docsBase}/providers/openai-compatible-providers/lmstudio`,
    packageName: "@ai-sdk/openai-compatible",
    providerFamily: "openai_compatible",
    accessMode: "local_runtime",
    availableInApp: true,
    defaultBaseUrl: "http://127.0.0.1:1234/v1",
    defaultModel: null,
    defaultMaxOutputTokens: 900,
    supportsModelFetch: true,
    supportsReasoningEffort: true,
    runtimeKind: "openai_compatible",
  },
  {
    id: "llama_cpp",
    label: "llama.cpp",
    description: "Local llama.cpp server through the OpenAI-compatible provider path.",
    authMode: "none",
    docsUrl: `${docsBase}/providers/openai-compatible-providers`,
    packageName: "@ai-sdk/openai-compatible",
    providerFamily: "openai_compatible",
    accessMode: "local_runtime",
    availableInApp: true,
    defaultBaseUrl: "http://127.0.0.1:8080/v1",
    defaultModel: null,
    defaultMaxOutputTokens: 900,
    supportsModelFetch: true,
    supportsReasoningEffort: true,
    runtimeKind: "openai_compatible",
  },
];

export const inferenceProviderDefinitionMap = Object.fromEntries(
  inferenceProviderDefinitions.map((provider) => [provider.id, provider]),
) as Record<InferenceProviderId, InferenceProviderDefinition>;

export function getInferenceProviderDefinition(providerId?: string | null) {
  if (!providerId) {
    return null;
  }

  return inferenceProviderDefinitionMap[providerId as InferenceProviderId] ?? null;
}

export function isLocalRuntimeProvider(providerId?: string | null) {
  return getInferenceProviderDefinition(providerId)?.accessMode === "local_runtime";
}

export function providerSupportsStoredApiKey(authMode: InferenceProviderAuthMode) {
  return authMode === "api_key" || authMode === "api_key_or_account";
}
